export const ROUTES = {
  home: "/",
  about: "/about",
  team: "/team",
  residential: "/residential-mortgage-options",
  commercial: "/commercial-financing",
  buyHome: "/resources/buy-a-home",
  refinance: "/resources/refinance",
  toolsHub: "/tools",
  calculator: "/tools/mortgage-calculator",
  valuation: "/tools/home-valuation",
  termComparison: "/tools/loan-term-comparison",
  refinanceBreakeven: "/tools/refinance-break-even",
  cashOutVsHelocHeloan: "/tools/cash-out-vs-heloc-vs-heloan",
  armVsFixed: "/tools/arm-vs-fixed",
  selfEmployedAffordability: "/tools/self-employed-affordability",
  dscr: "/tools/dscr-calculator",
  debtConsolidationSavings: "/tools/debt-consolidation-savings",
  rateBuydown: "/tools/rate-buydown-calculator",
  rentVsBuy: "/tools/rent-vs-buy",
  contact: "/contact",
  privacy: "/privacy-policy",
  terms: "/terms-of-use",
} as const;

export type RouteValue = (typeof ROUTES)[keyof typeof ROUTES];
